[package]
name = "docli-render"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
docli-core = { path = "../docli-core", version = "0.1.0" }
docli-query = { path = "../docli-query", version = "0.1.0" }
anyhow.workspace = true
serde.workspace = true
similar.workspace = true
tempfile.workspace = true
