[package]
name = "lira-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
fs2.workspace = true
lira-core = { path = "../lira-core" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3"
