[package]
name = "docli-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "docli"
path = "src/main.rs"

[dependencies]
clap.workspace = true
docli-core = { path = "../docli-core", version = "0.1.0" }
docli-create = { path = "../docli-create", version = "0.1.0" }
docli-kb = { path = "../docli-kb", version = "0.1.0" }
docli-patch = { path = "../docli-patch", version = "0.1.0" }
docli-query = { path = "../docli-query", version = "0.1.0" }
docli-render = { path = "../docli-render", version = "0.1.0" }
docli-schema = { path = "../docli-schema", version = "0.1.0" }
roxmltree.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
zip.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
zip.workspace = true
